[package]
name = "youtube-client"
version = "0.1.0"
authors = ["Kil0meters kil0meters@protonmail.com"]

[dependencies]
glib = "^0"
pango = "^0"
htmlescape = "0.3"
gtk = { version = "0.1.0", features = ["v3_20"] }
youtube_api = { path = "youtube_api" }
